front:
  image: webscope/nginx-php-fpm
  environment:
    - VIRTUAL_HOST=laravel.docker.local
  volumes_from:
    - www
    - sites
  links:
    - mysql:mysql
    - redis:predis

www:
  image: tianon/true
  volumes:
    - ./www:/var/www

sites:
  image: tianon/true
  volumes:
    - ./sites:/etc/nginx/sites-enabled

mysql:
  image: mysql
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: project_db

artisan:
   image: spiralout/dartisan
   volumes_from:
     - www
   links:
      - mysql:mysql
      - redis:predis
   expose:
    - "3306"

nodejs:
  image: spiralout/dnodejs
  volumes_from:
     - www

redis:
   image: spiralout/alpine-redis
   volumes_from:
     - redis-data
   ports:
     - "6379"

redis-data:
  image: tianon/true
  volumes:
    - ./redis-data:/data
